name: Melos
options:
  createIntermediateGroups: true
  deploymentTarget:
    iOS: "15.0"

targets:
  Melos:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Melos
        excludes:
          - "**/*.plist"
          - "**/*.entitlements"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.melos.app
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5"
        INFOPLIST_FILE: Melos/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: Melos/Resources/Melos.entitlements
        CODE_SIGN_STYLE: Automatic
        TARGETED_DEVICE_FAMILY: "1"
        GENERATE_INFOPLIST_FILE: false
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
          CODE_SIGN_IDENTITY: "-"
        Release:
          SWIFT_OPTIMIZATION_LEVEL: -O
          CODE_SIGN_IDENTITY: "-"
